### ISSUE TITLE
ERD 설계

### ISSUE THREAD

**Issue by JAEHEE25** [Duaily/backend#9]

**Comment by dldmsql** [comment]
## 2차 ERD 설계 공유

![2차](https://user-images.githubusercontent.com/61505572/196033601-3550a14b-cd02-4c20-9f9e-415a0ddf5946.png)

Entity class로 전환 작업 중입니다.

**Comment by dldmsql** [comment]
<img width="1351" alt="image" src="https://user-images.githubusercontent.com/61505572/196037154-4f753e2a-0672-4acd-8fd5-4559fde3732e.png">


house 테이블 생성에서 오류 발생 -> 문제점 찾는 중

**Comment by dldmsql** [comment]
![2차 (1)](https://user-images.githubusercontent.com/61505572/196037195-148f6f5e-6817-47f1-9b3a-dbe044769883.png)

UserHouse 삭제 -> House로 처리하는 쪽으로 수정 중

**Comment by dldmsql** [comment]
house table create 시 오류 원인 :: `usage` 필드명 때문.
MySQL 에서 usage 키워드가 예약어이기 때문에, DDL에서 오류가 계속 발생했던 것임.

**Comment by dldmsql** [comment]
[여기](https://ryulstudy.tistory.com/67) 참고해서 주소 필드 결정하면 될 거 같음.

우편번호 | 주소 | 상세주소 순으로

**Comment by dldmsql** [comment]
[여기](https://victorydntmd.tistory.com/m/209) 참고.

join 전략 적용

**Comment by dldmsql** [comment]
![erd_2](https://user-images.githubusercontent.com/61505572/196708827-35589de2-abf5-4272-a557-3880c440b998.png)

3차 erd 설계
